on:
  push:
  workflow_dispatch: # manual triggering

jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.11"]  

    steps:  
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:  
          python-version: ${{ matrix.python-version }} 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r IAC_CounterFunction/requirements.txt

      - name: Set up environment variables
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Python tests
        run: |
          cd IAC_CounterFunction/tests
          ls
          python test-function_app.py
